package com.ethics4eu.ethics4eu.documents;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@Configuration
public class DocumentsConfig {

    @Bean
    CommandLineRunner commandLineRunner(
            DocumentsRepository repository){
            return args -> {
                Documents HolsteinDodigCrnkovic18 = new Documents("HolsteinDodig-Crnkovic18", null, null, null, null, "Computing: AI. Ethics: Autonomy. Industry: Transport, Robotics", null, "Holstein, Tobias and Dodig-Crnkovic, Gordana", "Proceedings of the International Workshop on Software Fairness", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "32--37", null, null, null, "Avoiding the intrinsic unfairness of the trolley problem", null, null, "2018", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents ShahriariShahriari17 = new Documents("ShahriariShahriari17", null, null, null, null, "Computing: AI. Ethics: Autonomy. Industry: Military, Economics", null, "Shahriari, Kyarash and Shahriari, Mana", "2017 IEEE Canada International Humanitarian Technology Conference (IHTC)", null, null, null, null, null, null, null, null, null, null, "1509062645", null, null, null, null, "197--201", "IEEE", null, null, "{IEEE standard review — Ethically aligned design: A vision for prioritizing human well-being with artificial intelligence and autonomous systems}", null, null, "2017", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents Thomson85 = new Documents("Thomson85", null, null, null, null, "Computing: AI. Ethics: Autonomy. Industry: Transport, Robotics", null, "Thomson, Judith Jarvis", null, null, null, null, null, null, "The Yale Law Journal", null, null, "6", null, null, null, null, null, null, "1395--1415", "JSTOR", null, null, "The trolley problem", null, "94", "1985", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents AlkhatiBernstein19 = new Documents("AlkhatiBernstein19", null, null, null, null, "Computing: Programming. Ethics: Bias. Industry: Government", null, "Alkhatib, Ali and Bernstein, Michael", "Proceedings of the 2019 CHI Conference on Human Factors in Computing Systems", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "1--13", null, null, null, "Street-Level Algorithms: A Theory at the Gaps Between Policy and Decisions", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents CelisKSV19 = new Documents("CelisKSV19", null, null, null, null, "Computing: Programming. Ethics: Bias", null, "Celis, L Elisa and Kapoor, Sayash and Salehi, Farnood and Vishnoi, Nisheeth", "Proceedings of the conference on fairness, accountability, and transparency", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "160--169", null, null, null, "Controlling polarization in personalization: An algorithmic framework", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents FloresBL16 = new Documents("FloresBL16", null, null, null, null, "Computing: Programming. Ethics: Bias. Industry: Crime, law", null, "Flores, Anthony W and Bechtel, Kristin and Lowenkamp, Christopher T", null, null, null, null, null, null, "Fed. Probation", null, null, null, null, null, null, null, null, null, "38", "HeinOnline", null, null, "False positives, false negatives, and false analyses: A rejoinder to machine bias: There's software used across the country to predict future criminals. and it's biased against blacks", null, "80", "2016", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents GonenGoldberg19 = new Documents("GonenGoldberg19", null, null, null, null, "Ethics: Bias.", null, "Gonen, Hila and Goldberg, Yoav", "Proceedings of NAACL-HLT", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "609--614", null, null, null, "Lipstick on a Pig: Debiasing Methods Cover up Systematic Gender Biases in Word Embeddings But do not Remove Them", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents KleinbergMR17 = new Documents("KleinbergMR17", null, null, null, null, "Ethics: Bias.", "Dagstuhl, Germany", "Jon Kleinberg and Sendhil Mullainathan and Manish Raghavan", "8th Innovations in Theoretical Computer Science Conference (ITCS 2017)", null, null, "Christos H. Papadimitriou", null, null, null, null, null, null, null, null, null, null, null, "	{10.4230/LIPIcs.ITCS.2017.43", "43:1--43:23", "Schloss Dagstuhl--Leibniz-Zentrum fuer Informatik", null, "Leibniz International Proceedings in Informatics (LIPIcs)", "{Inherent Trade-Offs in the Fair Determination of Risk Scores}", null, "67", "2017", null, null, null, null, null, null, null, null, null, null, null, null, "InProceedings");
                Documents PassiBarocas19 = new Documents("PassiBarocas19", null, null, null, null, "Ethics: Bias", null, "Passi, Samir and Barocas, Solon", "Proceedings of the Conference on Fairness, Accountability, and Transparency", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "39--48", null, null, null, "Problem formulation and fairness", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents RajiBuolamwini19 = new Documents("RajiBuolamwini19", null, null, null, null, "Ethics: Bias. Industry: Economics", null, "Raji, Inioluwa Deborah and Buolamwini, Joy", "Proceedings of the 2019 AAAI/ACM Conference on AI, Ethics, and Society", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "429--435", null, null, null, "Actionable auditing: Investigating the impact of publicly naming biased performance results of commercial {AI} products", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents RomanovETAL19 = new Documents("RomanovETAL19", null, null, null, null, "Ethics: Bias.", null, "Romanov, Alexey and De-Arteaga, Maria and Wallach, Hanna and Chayes, Jennifer and Borgs, Christian and Chouldechova, Alexandra and Geyik, Sahin and Kenthapadi, Krishnaram and Rumshisky, Anna and Kalai, Adam", "Proceedings of the 2019 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies, Volume 1 (Long and Short Papers)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "4187--4195", null, null, null, "What's in a Name? Reducing Bias in Bios without Access to Protected Attributes", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents SelbstBFVV19 = new Documents("SelbstBFVV19", null, null, null, null, "Ethics: Bias", null, "Selbst, Andrew D and Boyd, Danah and Friedler, Sorelle A and Venkatasubramanian, Suresh and Vertesi, Janet", "Proceedings of the Conference on Fairness, Accountability, and Transparency", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "59--68", null, null, null, "Fairness and abstraction in sociotechnical systems", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents Shah18 = new Documents("Shah18", null, null, null, null, "Ethics: Bias.", null, "Shah, Hetan", null, null, null, null, null, null, "Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences", null, null, "2128", null, null, null, null, null, null, "20170362", "The Royal Society Publishing", null, null, "Algorithmic accountability", null, "376", "2018", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents SharifiMalvajerdiKR19 = new Documents("Sharifi-MalvajerdiKR19", null, null, null, null, "Computing: Programming. Ethics: Bias", null, "Sharifi-Malvajerdi, Saeed and Kearns, Michael and Roth, Aaron", "Advances in Neural Information Processing Systems", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "8240--8249", null, null, null, "Average Individual Fairness: Algorithms, Generalization and Experiments", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents Hutchinson01 = new Documents("Hutchinson01", null, null, null, null, "Ethics: Discrimination", null, "Hutchinson, Jamie", null, null, null, null, null, null, "IEEE Professional Communication Society Newsletter", null, null, "3", null, null, null, null, null, null, "1--7", null, null, null, "Culture, communication, and an information age madonna", null, "45", "2001", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents Hollander03 = new Documents("Hollander03", null, null, null, null, "Ethics: Intellectual Property", null, "Hollander, Andrew Joseph", null, null, null, null, null, null, "Duke Law \\& Technology Review", null, null, "1", null, null, null, null, null, null, "1--13", "Duke University School of Law", null, null, "Patenting Computer Data Structures: The Ghost, the Machine and the Federal Circuit", null, "2", "2003", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents Albrechtslund07 = new Documents("Albrechtslund07", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Albrechtslund, Anders", "Proceedings of the seventh international conference of computer ethics philosophical enquiry, San Diego, USA: University of San Diego", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "7--16", null, null, null, "{House 2.0: towards an ethics for surveillance in intelligent living and working environments}", null, null, "2007", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents Allen12 = new Documents("Allen12", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Allen, Anita L", null, null, null, null, null, null, "St. Thomas Law Review", null, null, "1", null, null, null, null, null, null, "1", "St. Thomas Law Review", null, null, "What Must We Hide: The Ethics of Privacy and the Ethos of Disclosure", null, "25", "2012", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents Arendt98 = new Documents("Arendt98", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Arendt, Hannah", "The human condition", "B", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "22 -- 78", "University of Chicago Press", null, null, "The Public and the Private Realm", null, null, "1998", null, null, null, null, null, null, null, null, null, null, null, null, "incollection");
                Documents CavoukianETAL09 = new Documents("CavoukianETAL09", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Cavoukian, Ann and others", null, null, null, null, null, null, "Information and Privacy Commissioner of Ontario, Canada", null, null, null, null, null, null, null, null, null, null, null, null, null, "Privacy by design: The 7 foundational principles", null, "5", "2009", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents JacobsAbowd03 = new Documents("JacobsAbowd03", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Jacobs, Anne R and Abowd, Gregory D", null, null, null, null, null, null, "IEEE Pervasive Computing", null, null, "4", null, null, "1536-1268", null, null, null, "78--84", "IEEE", null, null, "{A framework for comparing perspectives on privacy and pervasive technologies}", null, "2", "2003", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents KnappSoylu13 = new Documents("KnappSoylu13", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Knapp, Karin R and Soylu, Ali", null, null, null, null, null, null, "Mustang Journal of Management and Marketing", null, null, null, null, null, null, null, null, null, "69--80", null, null, null, "Technology: The good, the bad, and the ugly. How technology is affecting employee privacy, work life balance, and workplace relationships", null, "2", "2013", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents LoiHFSC19 = new Documents("LoiHFSC19", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Loi, Michele and Heitz, Christoph and Ferrario, Andrea and Schmid, Anita and Christen, Markus", "2019 6th Swiss Conference on Data Science (SDS)", null, null, null, null, null, null, null, null, null, null, "1728131057", null, null, null, null, "6--12", "IEEE", null, null, "{Towards an ethical code for data-based business}", null, null, "2019", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents MiltgenLancelotPeyratGuillard14 = new Documents("MiltgenLancelotPeyrat-Guillard14", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Miltgen, Caroline Lancelot and Peyrat-Guillard, Dominique", null, null, null, null, null, null, "European Journal of Information Systems", "mar", null, "2", null, null, "0960-085X", "https://doi.org/10.1057/ejis.2013.17", null, "10.1057/ejis.2013.17", "103--125", "Taylor & Francis", null, null, "{Cultural and generational influences on privacy concerns: a qualitative study in seven European countries}", null, "23", "2014", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents Vatcha20 = new Documents("Vatcha20", null, null, null, null, "Industry: Academia. Ethics: Privacy and Data Protection", null, "Amy Vatcha", null, null, null, null, null, null, "iSCHANNEL - Information Systems student journal (LSE)", null, null, "1", null, null, null, null, null, null, "4--9", "Houghton St Press", null, null, "Workplace Surveillance Outside the Workplace: An Analysis of E-Monitoring Remote Employees", null, "15", "2020", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents Bensur14 = new Documents("Bensur14", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Bensur, Gariella E", null, null, null, null, null, null, "Cornell L. Rev.", null, null, null, null, null, null, null, null, null, "1191", "HeinOnline", null, null, "Cover your Webcam: The ECPA's Lack of Protection against Software That Could Be Watching You", null, "100", "2014", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents Chassang17 = new Documents("Chassang17", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Chassang, Gauthier", null, null, null, null, null, null, "ecancermedicalscience", null, null, null, null, null, null, null, null, null, null, "ecancer Global Foundation", null, null, "The impact of the {EU} general data protection regulation on scientific research", null, "11", "2017", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents HijmansRaab18 = new Documents("HijmansRaab18", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Hijmans, Hielke and Raab, Charles D", null, null, null, null, null, null, "Commentary on the General Data Protection Regulation, Cheltenham: Edward Elgar (2018, Forthcoming)", null, null, null, null, null, null, null, null, null, null, null, null, null, "Ethical Dimensions of the GDPR", null, null, "2018", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents KosinskiStillwellGraepel12 = new Documents("KosinskiStillwellGraepel12", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Kosinski, Michal and Stillwell, David and Graepel, Thore", null, null, null, null, null, null, "Proceedings of the national academy of sciences", null, null, "15", null, null, null, null, null, null, "5802--5805", "National Acad Sciences", null, null, "Private traits and attributes are predictable from digital records of human behavior", null, "110", "2013", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents vanAlsenoy17 = new Documents("vanAlsenoy17", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Van Alsenoy, Brendan", null, null, null, null, null, null, "KU Leuven", null, null, null, null, null, null, null, null, null, null, "Maklu", null, null, "Reconciling the (extra) territorial reach of the GDPR with public international law", null, null, "2017", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents TenePolonetsky13 = new Documents("TenePolonetsky13", null, null, null, null, "Ethics: Privacy and Data Protection", null, "Tene, Omer and Polonetsky, Jules", null, null, null, null, null, null, "Yale JL \\& Tech.", null, null, null, null, null, null, null, null, null, "59", "HeinOnline", null, null, "A theory of creepy: technology, privacy and shifting social norms", null, "16", "2013", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents Greengard21 = new Documents("Greengard21", null, null, null, null, "Ethics: Safety and security", null, "Greengard, Samuel", null, null, null, null, null, null, "Communications of the ACM", null, null, "4", null, null, null, null, null, null, "15--17", "ACM New York, NY, USA", null, null, "The worsening state of ransomware", null, "64", "2021", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents AvgeriouETAL20 = new Documents("AvgeriouETAL20", null, null, null, null, "Ethics: Technical Debt", null, "Avgeriou, Paris C and Taibi, Davide and Ampatzoglou, Apostolos and Fontana, Francesca Arcelli and Besker, Terese and Chatzigeorgiou, Alexandros and Lenarduzzi, Valentina and Martini, Antonio and Moschou, Nasia and Pigazzini, Ilaria and others", null, null, null, null, null, null, "IEEE Software", null, null, null, null, null, null, null, null, null, null, "IEEE", null, null, "An overview and comparison of technical debt measurement tools", null, null, "2020", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents BognerVG21 = new Documents("BognerVG21", null, null, null, null, "Ethics: Technical Debt", null, "Bogner, Justus and Verdecchia, Roberto and Gerostathopoulos, Ilias", null, null, null, null, null, null, "arXiv preprint arXiv:2103.09783", null, null, null, null, null, null, null, null, null, null, null, null, null, "Characterizing Technical Debt and Antipatterns in AI-Based Systems: A Systematic Mapping Study", null, null, "2021", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents CodabuxWilliams13 = new Documents("CodabuxWilliams13", null, null, null, null, "Ethics: Technical Debt", null, "Codabux, Zadia and Williams, Byron", "2013 4th International Workshop on Managing Technical Debt (MTD)", null, null, null, null, null, null, null, null, null, "IEEE", null, null, null, null, null, "8--15", null, null, null, "Managing technical debt: An industrial case study", null, null, "2013", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents LenarduzziBTMF21 = new Documents("LenarduzziBTMF21", null, null, null, null, "Ethics: Technical Debt", null, "Lenarduzzi, Valentina and Besker, Terese and Taibi, Davide and Martini, Antonio and Fontana, Francesca Arcelli", null, null, null, null, null, null, "Journal of Systems and Software", null, null, null, null, null, null, null, null, null, "110827", "Elsevier", null, null, "A systematic literature review on technical debt prioritization: Strategies, processes, factors, and tools", null, "171", "2021", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents LiAvgeriouLiang15 = new Documents("LiAvgeriouLiang15", null, null, null, null, "Ethics: Technical Debt", null, "Li, Zengyang and Avgeriou, Paris and Liang, Peng", null, null, null, null, null, null, "Journal of Systems and Software", null, null, null, null, null, null, null, null, null, "193--220", "Elsevier", null, null, "A systematic mapping study on technical debt and its management", null, "101", "2015", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents MeloFLS21 = new Documents("MeloFLS21", null, null, null, null, "Ethics: Technical Debt", null, "Melo, Ana and Fagundes, Roberta and Lenarduzzi, Valentina and Santos, Williams", null, null, null, null, null, null, "arXiv preprint arXiv:2105.14232", null, null, null, null, null, null, null, null, null, null, null, null, null, "Identification and Measurement of Technical Debt Requirements in Software Development: a Systematic Literature Review", null, null, "2021", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents Petrozzino21 = new Documents("Petrozzino21", null, null, null, null, "Ethics: Technical Debt", null, "Petrozzino, Catherine", null, null, null, null, null, null, "AI and Ethics", null, null, null, null, null, null, null, null, null, "1--4", "Springer", null, null, "Who pays for ethical debt in AI?", null, null, "2021", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents RantalaMantyla20 = new Documents("RantalaMantyla20", null, null, null, null, "Ethics: Technical Debt", null, "Rantala, Leevi and M{\"a}ntyl{\"a}, Mika", null, null, null, null, null, null, "Software Quality Journal", null, null, "4", null, null, null, null, null, null, "1551--1579", "Springer", null, null, "Predicting technical debt from commit contents: reproduction and extension with automated feature selection", null, "28", "2020", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents RiosDeMS18 = new Documents("RiosDeMS18", null, null, null, null, "Ethics: Technical Debt", null, "Rios, Nicolli and de Mendon{\\c{c}}a Neto, Manoel Gomes and Sp{\\'\\i}nola, Rodrigo Oliveira", null, null, null, null, null, null, "Information and Software Technology", null, null, null, null, null, null, null, null, null, "117--145", "Elsevier", null, null, "A tertiary study on technical debt: Types, management strategies, research trends, and base information for practitioners", null, "102", "2018", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents SpinolaZVSS19 = new Documents("SpinolaZVSS19", null, null, null, null, "Ethics: Technical Debt", null, "Sp{\\'\\i}nola, Rodrigo O and Zazworka, Nico and Vetro, Antonio and Shull, Forrest and Seaman, Carolyn", null, null, null, null, null, null, "Journal of the Brazilian Computer Society", null, null, "1", null, null, null, null, null, null, "1--21", "SpringerOpen", null, null, "Understanding automated and human-based technical debt identification approaches-a two-phase study", null, "25", "2019", null, null, null, null, null, null, null, null, null, null, null, null, "article");
                Documents TamburriKLvV13 = new Documents("TamburriKLvV13", null, null, null, null, "Ethics: Technical Debt", null, "Tamburri, Damian A and Kruchten, Philippe and Lago, Patricia and van Vliet, Hans", "2013 6th International Workshop on Cooperative and Human Aspects of Software Engineering (CHASE)", null, null, null, null, null, null, null, null, null, "IEEE", null, null, null, null, null, "93--96", null, null, null, "What is social debt in software engineering?", null, null, "2013", null, null, null, null, null, null, null, null, null, null, null, null, "inproceedings");
                Documents VogelHeuserBi21 = new Documents("Vogel-HeuserBi21", null, null, null, null, "Ethics: Technical Debt", null, "Vogel-Heuser, Birgit and Bi, Fandi", null, null, null, null, null, null, "Journal of Systems and Software", null, null, null, null, null, null, null, null, null, "110809", "Elsevier", null, null, "Interdisciplinary effects of technical debt in companies with mechatronic products—a qualitative study", null, "171", "2021", null, null, null, null, null, null, null, null, null, null, null, null, "article");

                repository.saveAll(
                        List.of(HolsteinDodigCrnkovic18, ShahriariShahriari17, Thomson85, AlkhatiBernstein19, CelisKSV19, FloresBL16, GonenGoldberg19, KleinbergMR17, PassiBarocas19, RajiBuolamwini19, RomanovETAL19, SelbstBFVV19, Shah18, SharifiMalvajerdiKR19, Hutchinson01, Hollander03, Albrechtslund07, Allen12, Arendt98, CavoukianETAL09, JacobsAbowd03, KnappSoylu13, LoiHFSC19, MiltgenLancelotPeyratGuillard14, Vatcha20, Bensur14, Chassang17, HijmansRaab18, KosinskiStillwellGraepel12, vanAlsenoy17, TenePolonetsky13, Greengard21, AvgeriouETAL20, BognerVG21, CodabuxWilliams13, LenarduzziBTMF21, LiAvgeriouLiang15, MeloFLS21, Petrozzino21, RantalaMantyla20, RiosDeMS18, SpinolaZVSS19, TamburriKLvV13, VogelHeuserBi21)
                );
            };
    }
}
